'''
CSI Utilities

DOES NOT REQUIRE THE PICOSCENES LIBRARY!

(Module)
Dimitry Melnikov, 2/17/25
'''

#################################################################################
############################## IMPORTS ##########################################
import tkinter as tk                # For file selection
from tkinter import filedialog      # For file selection

import numpy as np                  # Numpy Processing
import scipy.io                     # Load data from .mat file
import os                           # To retrive files

#################################################################################
############################# FUNCTIONS #########################################
def loadCSIfromMAT(csiPath=""):
    """ Load Parsed CSI from .mat file 

    Args:
        csiPath (string, optional): Absolute path to .mat file. Defaults to None.

    Returns:
        [
            Hest,           # CSI itself [AT AR S K]
            centerFreq,     # Center/Carrier Frequency for collected CSI
            chanBW,         # Channel Bandwidth (Hz)
            elemPos,        # Element Positions [[X0, Y0, Z0], [X1, Y1, Z1], ...]
            loadedStruct    # Source Struct
            csiPath         # Path to loaded CSI File
        
        ]: Tuple with variables of interest.
    """
    initialdir = os.getcwd() # Get the default
    if (not os.path.isfile(csiPath)) and (not (csiPath is "")):
        print(f"File path invalid for csiPath. Bringing up GUI dialog.")
        initialdir = os.path.dirname(csiPath) # We have the directory name for the CSI Path, if it's invalid.

    if (csiPath is "") or (not os.path.isfile(csiPath)):
        # Do GUI interface if path not specified
        # Ask the user to select a single file name.
        csiPath = filedialog.askopenfilename(initialdir=initialdir,
                                            title="Please select the CSI Source File:",
                                            filetypes=[('mat files', '.mat'), ('all files', '.*')])
    # Load in the Matlab File
    loadedStruct = scipy.io.loadmat(csiPath)

    # Stick everything into a tuple.
    Hest            = loadedStruct['outputMatrix']  # CSI Itself [AT AR S K]
    centerFreq      = loadedStruct['centerFreq']    # Center/Carrier Frequency for collected CSI (Hz)
    chanBW          = loadedStruct['chanBW']        # Channel Bandwidth (Hz)
    subcFreq        = loadedStruct['subcFreq']      # Subcarrier Frequencies (Hz)
    elemPos         = loadedStruct['elemPos']       # Positions for each element [[X0, Y0, Z0], [X1, Y1, Z1], ...]

    return [Hest, centerFreq, chanBW, subcFreq, elemPos, loadedStruct, csiPath]
    



def getSubcFreq(centerFreq, chanBW, S):
    """ Return Subcarrier Frequencies for Given CSI
        APPROXIMATION! THIS WILL LIKELY BE WRONG DEPENDING ON HOW THE CSI WAS COLLECTED!!

    Args:
        centerFreq (integer): Center/Carrier Frequency (Hz)
        chanBW (integer): Channel Bandwidth (Hz)
        S (integer): Number of Subcarriers. ([AT AR S K] ~ np.size(Hest, 2))

    Returns:
        np.array: Numpy array of size `S` corresponding to the frequencies of each subcarrier
    """
    # Calculate the Frequency Axis
    subcSpacing = chanBW / S # Channel BW / Num Subcarriers (S)
    subcFreq    = np.linspace(centerFreq - chanBW/2, \
                              centerFreq + chanBW/2, \
                              S)
    subcFreq = subcFreq.flatten()

    return subcFreq

def getSubcFreqFromCSI(frame):
    """ Return Subcarrier Frequencies as generated by a Picoscenes Frame

    Args:
        frame (picoscenesOutput.raw[0]): Raw Picoscenes Frame

    Returns:
        (arr): Array with size frame['CSI']['numTones'] corresponding to the Subcarrier Frequencies (Hz)
                associated with each subcarrier/tone.
    """
    centerFreq  = frame['CSI']['CarrierFreq']               # 2 447 000 (Hz)
    subcBW      = frame['CSI']['SubcarrierBandwidth']       # 321500 (Hz)
    subcInd     = frame['CSI']['SubcarrierIndex']           # [-26, -25, ..., -1, 0, 1, ..., 25, 26]

    return centerFreq + np.array(subcInd)*subcBW # Shift up, then apply bandwidths.